### ISSUE TITLE
how to make scan continues without refresing the page.. 

### ISSUE THREAD

**Issue by didikurnia** [code-kotis/barcode-scanner#39] opened 2018-01-04 12:52 UTC
hello, can u help me to make this scan qrcode continously without refresh ?

i try to call the scan(); after app_dialog close. its not working...

**Comment by gokulkrishh** [comment] 2018-06-01 03:38
@didikurnia Not sure why it is not working for you. I tested this scenario and its working fine for me. Give us some more inputs on how to re-produce this. Thanks

**Comment by gokulkrishh** [comment] 2018-08-12 06:18
closing this as its I am not able to reproduce.

**Closed as completed by gokulkrishh** 2018-08-12 06:18 UTC
Labels: Not able to reproduce
