### ISSUE TITLE
possible bug with URLs

### ISSUE THREAD

**Issue by earwickerh** [code-kotis/barcode-scanner#87] opened 2020-02-04 08:49 UTC
When I scan a qr for a non- http:// URL, I don't get the "open" button. However if I first go to an http url->tap "close" -> then go to a non http:// url the "open" button shows up. Using firefox on android.

p.s. Great App! Thank you!

**Comment by gokulkrishh** [comment] 2020-02-04 12:09
@earwickerh Seems like a BUG 🐞. Thanks for reporting. I will check the issue.

**Comment by gokulkrishh** [comment] 2020-02-22 07:34
@earwickerh I am not able to reproduce this issue. It works fine for both http, https url. Closing the issue for now. Feel free to re-open if needed!

**Closed as completed by gokulkrishh** 2020-02-22 07:34 UTC
Labels: bug, Not able to reproduce
